.\" Copyright (c) 1993 Michael Haardt (michael@moria.de), Fri Apr  2 11:32:09 MET DST 1993
.\"
.\" This is free documentation; you can redistribute it and/or
.\" modify it under the terms of the GNU General Public License as
.\" published by the Free Software Foundation; either version 2 of
.\" the License, or (at your option) any later version.
.\"
.\" The GNU General Public License's references to "object code"
.\" and "executables" are to be interpreted as the output of any
.\" document formatting or typesetting system, including
.\" intermediate and printed output.
.\"
.\" This manual is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public
.\" License along with this manual; if not, write to the Free
.\" Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111,
.\" USA.
.\" 
.\" Modified Sat Jul 24 17:06:52 1993 by Rik Faith (faith@cs.unc.edu)
.\" Modified Sun Jan 14 00:34:09 1996 by Andries Brouwer (aeb@cwi.nl)
.TH INTRO 5 "24 July 1993" "Linux" "리눅스 프로그래머 매뉴얼"
.SH 이름
intro \- 파일 포맷에 대한 소개
.SH 설명
이 장은 다양한 파일 포맷과 프로토콜과 만약 있다면 사용되는 C 구조체를
설명한다.
.SH 저자
저자와 저작권에 관해서는 각 매뉴얼 페이지의 헤더를 보아라.
이것들은 페이지 마다 다르다.
.SH 역자
배성훈 <plodder@kldp.org>, 2000년 4월 29일
