.\" Copyright (c) 1993 Michael Haardt (michael@moria.de), Fri Apr  2 11:32:09 MET DST 1993
.\"
.\" This is free documentation; you can redistribute it and/or
.\" modify it under the terms of the GNU General Public License as
.\" published by the Free Software Foundation; either version 2 of
.\" the License, or (at your option) any later version.
.\"
.\" The GNU General Public License's references to "object code"
.\" and "executables" are to be interpreted as the output of any
.\" document formatting or typesetting system, including
.\" intermediate and printed output.
.\"
.\" This manual is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public
.\" License along with this manual; if not, write to the Free
.\" Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111,
.\" USA.
.\" 
.\" Modified Sun Jul 25 11:06:27 1993 by Rik Faith (faith@cs.unc.edu)
.TH SECURETTY 5 "December 29 1992" "Linux" "리눅스 프로그래머 매뉴얼"
.SH 이름
securetty \- root가 로그인 할 수 있는 tty 리스트 파일
.SH 설명
\fB/etc/securetty\fP 는
.BR login (1)
에 의해 사용된다;
root login이 허용되는 tty 장치명
(
.IR /dev/ 
없이 한 행 마다 )
을 포함하고 있다.
.SH 파일
/etc/securetty
.SH 관련 항목
.BR login (1)
.SH 역자
배성훈 <plodder@kldp.org>, 2000년 5월 13일
