.\" Copyright 1995 Jim Van Zandt <jrv@vanzandt.mv.com>
.\"
.\" Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\"
.\" Permission is granted to copy and distribute modified versions of this
.\" manual under the conditions for verbatim copying, provided that the
.\" entire resulting derived work is distributed under the terms of a
.\" permission notice identical to this one.
.\" 
.\" Since the Linux kernel and libraries are constantly changing, this
.\" manual page may be incorrect or out-of-date.  The author(s) assume no
.\" responsibility for errors or omissions, or for damages resulting from
.\" the use of the information contained herein.  The author(s) may not
.\" have taken the same level of care in the production of this manual,
.\" which is licensed free of charge, as they might when working
.\" professionally.
.\" 
.\" Formatted or processed versions of this manual, if unaccompanied by
.\" the source, must acknowledge the copyright and authors of this work.
.\"
.\" changed `square root' into `cube root' - aeb, 950919
.\"
.TH CBRT 3  "1995년 9월 16일" "" "리눅스 프로그래머 매뉴얼"
.SH 이름
cbrt \- 세제곱 루트 함수
.SH 사용법
.nf
.B #include <math.h>
.sp
.BI "double cbrt ( double " x " );"
.fi
.SH 설명
\fBcbrt()\fP 함수는 \fIx\fP의 세제곱 루트 값을 반환한다.
이 함수는 실패할수 없다; 모든 표현 가능한 실수 값은 표현할수 있는 실 세제곱 루트값을 가진다.
.SH 호환
\fBcbrt\fP 는 GNU 확장이다.
.SH 관련 항목
.BR sqrt "(3), " pow (3)
.SH 역자
정강훈 <skyeyes@soback.kornet.net>, 2001년 5월 24일
