.\" Copyright 1993 David Metcalfe (david@prism.demon.co.uk)
.\"
.\" Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\"
.\" Permission is granted to copy and distribute modified versions of this
.\" manual under the conditions for verbatim copying, provided that the
.\" entire resulting derived work is distributed under the terms of a
.\" permission notice identical to this one
.\" 
.\" Since the Linux kernel and libraries are constantly changing, this
.\" manual page may be incorrect or out-of-date.  The author(s) assume no
.\" responsibility for errors or omissions, or for damages resulting from
.\" the use of the information contained herein.  The author(s) may not
.\" have taken the same level of care in the production of this manual,
.\" which is licensed free of charge, as they might when working
.\" professionally.
.\" 
.\" Formatted or processed versions of this manual, if unaccompanied by
.\" the source, must acknowledge the copyright and authors of this work.
.\"
.\" References consulted:
.\"     Linux libc source code
.\"     Lewine's _POSIX Programmer's Guide_ (O'Reilly & Associates, 1991)
.\"     386BSD man pages
.\" Modified Sat Jul 24 19:51:25 1993 by Rik Faith (faith@cs.unc.edu)
.\" Modified Sat Jun  8 13:21:29 1996 by aeb
.TH COSH 3  "1993년 6월 13일" "" "리눅스 프로그래머 매뉴얼"
.SH 이름
cosh \- 쌍곡선 코사인 함수
.SH 사용법
.nf
.B #include <math.h>
.sp
.BI "double cosh(double " x );
.fi
.SH 설명
\fBcosh()\fP 함수는 \fIx\fP의 쌍곡선 코사인 값을 반환하며, 수학적으로 (exp(x) + exp(-x)) / 2로 정의되어 있다.
.SH 호환
SVID 3, POSIX, BSD 4.3, ISO 9899
.SH 관련 항목
.BR acosh "(3), " asinh "(3), " atanh "(3), " sinh "(3), " tanh (3)
.SH 역자
정강훈 <skyeyes@soback.kornet.net>, 2001년 5월 24일
