.\" Copyright 1993 David Metcalfe (david@prism.demon.co.uk)
.\"
.\" Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\"
.\" Permission is granted to copy and distribute modified versions of this
.\" manual under the conditions for verbatim copying, provided that the
.\" entire resulting derived work is distributed under the terms of a
.\" permission notice identical to this one
.\" 
.\" Since the Linux kernel and libraries are constantly changing, this
.\" manual page may be incorrect or out-of-date.  The author(s) assume no
.\" responsibility for errors or omissions, or for damages resulting from
.\" the use of the information contained herein.  The author(s) may not
.\" have taken the same level of care in the production of this manual,
.\" which is licensed free of charge, as they might when working
.\" professionally.
.\" 
.\" Formatted or processed versions of this manual, if unaccompanied by
.\" the source, must acknowledge the copyright and authors of this work.
.\"
.\" References consulted:
.\"     Linux libc source code
.\"     Lewine's _POSIX Programmer's Guide_ (O'Reilly & Associates, 1991)
.\"     386BSD man pages
.\" Modified Sat Jul 24 18:28:24 1993 by Rik Faith (faith@cs.unc.edu)
.TH RINT 3  "1993년 6월 6일" "" "리눅스 프로그래머 매뉴얼"
.SH 이름
rint \- 가장 가까운 정수로 라운딩
.SH 사용법
.nf
.B #include <math.h>
.sp
.BI "double rint(double " x );
.fi
.SH 설명

\fBrint()\fP 함수는  \fIx\fP를 일반적인 라운딩 모드에 따라 정수 값으로
라운딩 한다. 기본적인 가운딩 모드는 가장 까까운 정수로 라운딩 하는 것이다.
.SH 반환값
\fBrint()\fP 함수는 부동 소수점 수로써 정수 값을 반환한다.
.SH 호환
BSD 4.3
.SH 관련 항목
.BR abs "(3), " ceil "(3), " fabs "(3), " floor "(3), " labs (3)
.SH 역자
정강훈 <skyeyes@soback.kornet.net>, 2001년 3월 8일
