.\" Copyright 1993 David Metcalfe (david@prism.demon.co.uk)
.\"
.\" Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\"
.\" Permission is granted to copy and distribute modified versions of this
.\" manual under the conditions for verbatim copying, provided that the
.\" entire resulting derived work is distributed under the terms of a
.\" permission notice identical to this one
.\" 
.\" Since the Linux kernel and libraries are constantly changing, this
.\" manual page may be incorrect or out-of-date.  The author(s) assume no
.\" responsibility for errors or omissions, or for damages resulting from
.\" the use of the information contained herein.  The author(s) may not
.\" have taken the same level of care in the production of this manual,
.\" which is licensed free of charge, as they might when working
.\" professionally.
.\" 
.\" Formatted or processed versions of this manual, if unaccompanied by
.\" the source, must acknowledge the copyright and authors of this work.
.\"
.\" References consulted:
.\"     Linux libc source code
.\"     Lewine's _POSIX Programmer's Guide_ (O'Reilly & Associates, 1991)
.\"     386BSD man pages
.\" Modified Sat Jul 24 18:01:24 1993 by Rik Faith (faith@cs.unc.edu)
.TH STRPBRK 3  "1993년 4월 12일" "" "리눅스 프로그래머 매뉴얼"
.SH 이름
strpbrk \- 문자열에서 문자들의 집합중 어떤 것을 찾는다.
.SH 사용법
.nf
.B #include <string.h>
.sp
.BI "char *strpbrk(const char *" s ", const char *" accept );
.fi
.SH 설명
\fBstrpbrk()\fP 함수는 문자열 \fIs\fP에서 문자열 \fIaccept\fP내의
문자들 중 하나가 처음 발견되는 곳을 찾는다.
.SH 반환값
\fBstrpbrk()\fP 함수는 \fIaccept\fP내 문자들 중 하나와 일치하는 \fIs\fP 내
문자에 대한 포인터를 반환하거나 어떤 문자도 발견되지 않는다면 NULL을 
반환한다.
.SH 호환
SVID 3, POSIX, BSD 4.3, ISO 9899
.SH 관련 항목
.BR index "(3), " memchr "(3), " rindex "(3), " strchr (3),
.BR strsep "(3), " strspn "(3), " strstr "(3), " strtok (3)
.SH 역자
정강훈 <skyeyes@soback.kornet.net>, 2001년 2월 24일
