.Id $Id: atd.8,v 1.1.1.1 2002/07/18 10:40:12 hhyoon Exp $
.TH ATD 8 "1997년 3월" local "리눅스 프로그래머 매뉴얼"
.SH 이름
atd \- 나중에 수행하려고 등록한 작업을 실행한다.
.SH 사용법
.B atd
.RB [ -l
.IR load_avg ]
.RB [ -b
.IR batch_interval ]
.RB [ -d ]
.RB [ -s ]
.SH 설명
.BR atd "는 " at(1) 으로
큐에 넣은 작업들을 실행한다.
.PP
.SH 옵션
.TP 8
.B -l
일괄 작업이 실행되지 않아야 하는 제한 부하 상황을 명시한다. 컴파일 시에
초기값으로 0.8이 사용된다.
.IR n 개의
CPU를 가진 SMP 시스템에서는
.IR n-1 보다
큰 값을 설정할 수도 있을 것이다.
.TP 8
.B -b
두 일괄 작업의 최소 시작 시간 간격을 초 단위로 명시한다. (기본값은 60)
.TP 8
.B -d
디버그; 
.BR syslog(3) 를 
사용하는 대신에 표준 에러로 에러 메시지를 출력한다.
.TP 8
.B -s
한 번에 at/batch 큐를 처리한다. 이는 이전 버전의
.BR at 과의
호환성을 위해 사용된다. 
.BR "atd -s" 는
오래된 
.B atrun
명령과 같다. 호환성을 위해 
.BR "atd -s" 를 
실행하는 
.B /usr/sbin/atrun
스크립트가 설치된다.
.SH 파일
.I /var/spool/atjobs
작업을 저장하는 디렉토리; 소유자 at, 모드 700이여야 한다.
.PP
.I /var/spool/atspool
결과를 저장하는 디렉토리; 소유자 at, 모드 700이여야 한다.
.PP
.IR /etc/at.allow ,
.IR /etc/at.deny
.B at 
시스템을 사용할 수 있는 사용자를 결정한다.
.SH 관련 항목
at(1), atrun(1), cron(1), crontab(1), syslog(3), at_deny(5), at_allow(5)
.SH 버그
.BR atd 의 
기능은 
.BR cron(1) 에
합쳐져야 한다.
.SH 역자
임종균 <hermes44@secsm.org>, 2000년 4월 27일
