.\" Rick Sladkey <jrs@world.std.com>
.\" In the public domain.
.\" Pathname modified by faith@cs.unc.edu
.TH CHROOT 8 "20 November 1993" "Linux 0.99" "Linux Programmer's Manual"
.SH 이름
chroot \- root 경로를 바꾸고 그곳에서 풀그림을 실행한다.
.SH 사용법
.BI chroot " 경로 풀그림" " [ " "인자 ..." " ]"
.SH 설명 
.B chroot
명령은 처리를 위한 root 경로(작업 경로)를 \fI경로\fR로 바꾸고, 
\fI풀그림\fR을 그곳에서 실행한다.
.SH "관련 항목"
.BR chroot (2)
.SH 만든이
Rick Sladkey <jrs@world.std.com>
