.\" Copyright 1993 Rickard E. Faith (faith@cs.unc.edu)
.\" May be distributed under the GNU General Public License
.TH IPCRM 8 "9 October 1993" "Linux 0.99" "Linux Programmer's Manual"
.SH 이름
ipcrm \- ipc에 대해서 지정한 리소스를 지운다.
.SH 사용법
.BI "ipcrm [ shm | msg | sem ] " id
.SH 설명
.B ipcrm
명령은 \fIid\fR로 지정한 리소스를 지운다.
.SH 관련 항목
.BR ipcs (8)
.SH 만든이
krishna balasubramanian (balasub@cis.ohio-state.edu)
