.\" Rick Sladkey <jrs@world.std.com>
.\" In the public domain.
.\" Path modifications by faith@cs.unc.edu
.TH SETSID 8 "20 November 1993" "Linux 0.99" "Linux Programmer's Manual"
.SH 이름
setsid \- 새 세션 안에서 한 풀그림을 실행한다.
.SH 사용법
.BI setsid " 풀그림" " [ " "인자 ..." " ]"
.SH 설명
.B setsid
명령은 \fI풀그림\fR을 새 세션안에서 실행한다.
.SH "관련 항목"
.BR setsid (2)
.SH 만든이
Rick Sladkey <jrs@world.std.com>
