.TH DIRCOLORS 1L \" -*- nroff -*-
.SH NAME
dircolors \- LS_COLOR 환경 변수를 지정하기 위해 사용하는 명령
.SH SYNOPSIS
.TP
\fBeval `dircolors\fR [\-b] [\-\-sh] [\-c] [\-\-csh] [\-\-help]
[\-\-version] [file]\fB`\fR
.SH DESCRIPTION
이 명령에 대해서는 \fBdircolors\fR \fI\-\-help\fR 명령으로 
명령 자제에서 제공하는 도움말을 참조하기 바란다.
.P
이 문서는 더이상 최신 정보를 담고 있지않다. 그래서, 
몇몇 틀릴 경우도 있고, 부족한 경우도 있을 것이다. 
완전한 매뉴얼을 원하면, Texinfo 문서를 참조하기 바란다.
