.TH DIRNAME 1L "GNU 쉘 유틸리티" "FSF" \" -*- nroff -*-
.SH 이름
dirname \- 화일명으로부터 디렉토리 아닌 접미사 제거
.SH 개요
.B dirname
화일명
.br
.B dirname
{\-\-help,\-\-version}
.SH 설명
이 맨페이지는 GNU 버전의
.BR dirname 
을 다룬다.
.B dirname
은 
.IR 화일명
중 마지막 슬래쉬 뒷부분을 제외한 부분을 출력한다.
만약
.I 화일명
이 단 하나의 구성요소로 되어 있다면,
.B dirname
은 현재 디렉토리를 의미하는 `.'를 출력할 것이다.
.SS 옵션
.TP
.I "\-\-help"
표준출력으로 사용법을 출력하고 정상적으로 종료한다.
.TP
.I "\-\-version"
표준출력으로 버전정보를 출력하고 정상적으로 종료한다.
