.TH FALSE 1L "GNU 쉘 유틸리티" "FSF" \" -*- nroff -*-
.SH 이름
false \- 아무 것도 하지 않으며 항상 실패한다.
.SH 개요
.B false
.br
.B false
{\-\-help,\-\-version}
.SH 설명
이 맨페이지는 GNU 버전의
.B false
를 다룬다.
(아마도 다른 버전도 마찬가지일 것이다)
.B false
를 아무 것도 행하지 않으며 단지 ``실패''를 의미하는 종료 상태 1 을 반환한다.
실패하는 명령이 필요한 쉘 스크립트의 내부에서 사용되곤 한다.
.SS 옵션
GNU
.B false
가 정확히 하나의 인수를 가지고 실행되면 다음과 같은 옵션이 인식된다:
.TP
.I "\-\-help"
표준출력으로 사용법을 출력하고 정상적으로 종료한다.
.TP
.I "\-\-version"
표준출력으로 버전정보를 출력하고 정상적으로 종료한다.
