.\"
.\" Copyright (c) 1999,2000 WU-FTPD Development Group.
.\" All rights reserved.
.\"
.\" Portions Copyright (c) 1980, 1985, 1988, 1989, 1990, 1991, 1993, 1994
.\" The Regents of the University of California.  Portions Copyright (c)
.\" 1993, 1994 Washington University in Saint Louis.  Portions Copyright
.\" (c) 1996, 1998 Berkeley Software Design, Inc.  Portions Copyright (c)
.\" 1998 Sendmail, Inc.  Portions Copyright (c) 1983, 1995, 1996, 1997 Eric
.\" P. Allman.  Portions Copyright (c) 1989 Massachusetts Institute of
.\" Technology.  Portions Copyright (c) 1997 Stan Barber.  Portions
.\" Copyright (C) 1991, 1992, 1993, 1994, 1995, 1996, 1997 Free Software
.\" Foundation, Inc.  Portions Copyright (c) 1997 Kent Landfield.
.\"
.\" Use and distribution of this software and its source code are governed
.\" by the terms and conditions of the WU-FTPD Software License ("LICENSE").
.\"
.\"     $Id: ftpcount.1,v 1.1.1.1 2002/07/18 10:40:11 hhyoon Exp $
.\"
.TH ftpcount 1
.SH 이름
ftpcount \- 각 class의 현재 user수를 보여준다.
.SH 문법
.B ftpcount
[
.B \-V
]
.SH 설명
.NXR "ftpcount command"
.NXR "system" "show ftpd usage"
.PN ftpcount
명령은 ftpaccess file에서 정의된 각 class에 대한 user의 수 또는 제한된
user의 현재 접속수를 보여준다.
.B \-V
옵션은 저작권과 버젼 정보를 출력한다.
.PN ftpcount.
.SH 관련 항목
ftpwho(1)
.SH 역자
김정균 <admin@oops.org> 2000년 8월 4일

