.\" 
.\" Version 1.4 of namei
.\"
.TH NAMEI 1 "Local"
.SH 이름
namei - 터미날 포인트가 발견되기 전까지 경로이름을 보여준다.
.SH 사용법
.B namei
.I [-mx]
.I 경로이름
.I "[ 경로이름 ... ]"
.SH 설명
\fI경로이름\fR에 사용될 인자는 유닉스 파일의 어떠한 형태
(심블릭 링크, 일반 파일, 경로, 기타등등)도 사용될 수 있다.
그러면, \fBnamei\fR는 그 \fI경로이름\fR에 관련된 모든 
파일을 보여준다. 
만약 심블릭 링크가 발견되면, 그 해당 링크한 원본 파일에 대해서도 
들여쓰기를 해서, 그 정보를 모두 보여준다. 
.PP
이 풀그림은 "too many levels of symbolic links
(너무 많은 수준으로 링크된 파일)"의 오류를 발견하는데, 
유용하게 쓰인다.
.PP
출력되는 각 줄의 처음에는 그 파일의 형태를 알리는 문자를 표시하는데, 
그것은 다음과 같다.
.LP
.nf
   f: = 입력된 \fI경로이름\fR
    d = 경로
    l = 심블릭 링크 (링크 대상이 된 파일은 다음에 들여쓰기로 보여준다.)
    s = 소켓
    b = 블럭 장치
    c = 캐릭터 장치
    - = 일반 파일
    ? = 알 수 없는 파일
.fi
.PP
.I Namei
명령은 현재 시스템에서 처리될 수 있는 최대 심블릭 갯수(다중 심블릭)에 
대한 유용한 정보를 제공한다.
.SH 옵션
.TP 8
.B -x
마운트 된 파일시스템의 경로에 대해서는 'd' 대신 'D'를 표시한다.
.TP 8
.B -m
ls(1)에서 사용하듯이 각 파일의 모드를 보여준다. 
예를 들면 'rwxr-xr-x'.
.SH 만든이
Roger Southwick  (rogers@amadeus.wr.tek.com)
.SH 벌레
있을지도 모름.
.SH CAVEATS
만약에 두 파일이 서로 심블릭 링크되어 순환되고 있는 상태라면, 
이 풀그림은 계속해서 그 정보를 보여준다. 
이때는 SIGINT 시그날(일반적으로 ^C)로 멈추어야한다.
.SH "관련 항목"
ls(1), stat(1)
