.TH NOHUP 1L "GNU 쉘 유틸리티" "FSF" \" -*- nroff -*-
.SH 이름
nohup \- Hangup에 무관하게 명령을 수행하고 tty아닌 곳에 출력을 하도록 한다.
.SH 개요
.B nohup
명령 [인수...]
.br
.B nohup
{\-\-help,\-\-version}
.SH 설명
이 맨페이지는 GNU 버전의
.BR nohup 
을 다룬다.
.B nohup
은
.I 명령
에 대하여 Hangup 신호를 무시한 채 수행하며 우선권을 5 만큼 증가시켜
여러분이 로그아웃한 후에도 계속 백그라운드로 실행할 수 있도록 해준다.
만약 표준출력이 tty 였다면 표준출력과 표준에러는 `nohup.out'이라는 화일에
추가된다. 쓰기 작업이 불가능한 경우에는 `$HOME/nohup.out' 화일에 추가된다.
그것도 불가능한 경우에는 실행이 되지 않는다.
.PP
If
.B nohup
은 `nohup.out' 또는 `$HOME/nohup.out' 화일을 생성하고 그룹/타인에게는 접근
권한을 부여하지 않는다. 만약 존재한다면 기존의 허가권을 변화시키지는 않는다.
.PP
.B nohup
은 실행한 명령을 자동으로 백그라운드로 보내지 않는다; 여러분은 명령행 뒤에
`&' 문자를 붙인다든지 하여 명시적으로 백그라운드로 보내주어야 한다.
.SS 옵션
GNU
.B nohup
이 단 하나의 인수를 가지고 실행되면 다음 옵션들이 인식된다:
.TP
.I "\-\-help"
표준출력으로 사용법을 출력하고 정상적으로 종료한다.
.TP
.I "\-\-version"
표준출력으로 버전정보를 출력하고 정상적으로 종료한다.
