.TH PATHCHK 1L "GNU 쉘 유틸리티" "FSF" \" -*- nroff -*-
.SH 이름
pathchk \- 화일명이 유효하며 이동성(portability)이 있는지 점검한다.
.SH 개요
.B pathchk
[-p] [\-\-portability] [\-\-help] [\-\-version] 화일명...
.SH 설명
이 맨페이지는 GNU 버전의
.BR pathchk 
를 다룬다.
각 
.IR 화일명 
에 대하여,
.B pathchk
는 다음과 같은 조건이 만족하지 않으면 메세지를 출력한다:
.br
\" 원래는 \(bu 이나 화면 출력이 제대로 안됨.
\- 
.I 화일명
에 속한 모든 디렉토리에 검색(실행) 허가권을 갖고 있다.
.br
\- 
.I 화일명
의 길이가 화일 시스템이 지원하는 최대 화일 길이를 넘지 않는다.
.br
\-
존재하는 디렉토리명에 대한
.I 화일명
의 각 요소 길이가 화일명 부분에 대한 화일 시스템의 최대 길이를 넘지 않는다.
.PP
종료 상태는 다음과 같다:
.nf
0 모든 화일명이 검사내용에 만족할 때
1 그 외.
.fi
.SS 옵션
.TP
.I "\-\-help"
표준출력으로 사용법을 출력하고 정상적으로 종료한다.
.TP
.I "\-p, \-\-portability"
현재 화일 시스템에서 길이 점검을 하는 것이 아니라 다른 시스템으로의 이동을
고려하여 POSIX.1 최소 규격에 맞는지 점검한다. 또한 화일명 안에 
이동성 문자 세트에 포함되지 않는 글자가 있는지 살펴본다.
.TP
.I "\-\-version"
표준출력으로 버전정보를 출력하고 정상적으로 종료한다
