.TH PRINTENV 1L "GNU 쉘 유틸리티" "FSF" \" -*- nroff -*-
.SH 이름
printenv \- 환경의 전부 또는 일부를 출력한다.
.SH 개요
.B printenv
[\-\-help] [\-\-version] [variable...]
.SH 설명
이 맨페이지는 GNU 버전의
.BR printenv 
를 설명한다.
만약 아무런 인수도 주어지지 않으면,
.B printenv
는 환경 전부를 출력한다.
하나 이상의 변수명이 주어지면 설정된 변수에 대해서는 값을 출력하고 그렇지
않은 변수에 대해서는 아무것도 출력하지 않는다.
.PP
종료 상태는 다음과 같다:
.nf
0 모든 변수가 존재할 때
1 적어도 하나의 변수가 존재하지 않을 때
2 쓰기 에러가 발생했을 때
.SS 옵션
.TP
.I "\-\-help"
표준출력으로 사용법을 출력하고 정상적으로 종료한다.
.TP
.I "\-\-version"
표준출력으로 버전정보를 출력하고 정상적으로 종료한다.
