.TH PWD 1L "GNU 쉘 유틸리티" "FSF" \" -*- nroff -*-
.SH 이름
pwd \- 현재/작업 디렉토리명을 출력한다
.SH 개요
.B pwd
.br
.B pwd
{\-\-help,\-\-version}
.SH 설명
이 맨페이지는 GNU 버전의
.BR pwd 
를 다룬다.
.B pwd
는 현재 디렉토리의 완전한 이름을 출력한다.
즉 출력된 이름의 모든 구성 요소들이 실제 디렉토리를 의미한다.
- 심볼릭 링크가 아니라.
.PP
대부분의 유닉스 쉘들은 내장 
.B pwd
명령으로 비슷한 기능을 제공하고 있다.
따라서 대부분의
.B pwd
명령은 지금 이것이 아니라 내부에서 수행되는 것일 것이다.
.SS 옵션
.TP
.I "\-\-help"
표준출력으로 사용법을 출력하고 정상적으로 종료한다.
.TP
.I "\-\-version"
표준출력으로 버전정보를 출력하고 정상적으로 종료한다.
