.TH SLEEP 1L "GNU 쉘 유틸리티" "FSF" \" -*- nroff -*-
.SH 이름
sleep \- 주어진 시간만큼 지연시킨다.
.SH 개요
.B sleep
[\-\-help] [\-\-version] number[smhd]...
.SH 설명
이 맨페이지는 GNU 버전의
.BR sleep 
을 다룬다.
.B sleep
은 명령행에서 주어진 인수들을 합한 만큼의 시간 동안 지연시킨다.
각 인수는 숫자이며 뒤에 단위가 올 수도 있다. 기본값은 초이다. 단위는
다음과 같다:
.IP s
초
.IP m
분
.IP h
시
.IP d
일
.SS 옵션
.TP
.I "\-\-help"
표준출력으로 사용법을 출력하고 정상적으로 종료한다.
.TP
.I "\-\-version"
표준출력으로 버전정보를 출력하고 정상적으로 종료한다.
