.TH TEE 1L "GNU 쉘 유틸리티" "FSF" \" -*- nroff -*-
.SH 이름
tee \- 표준입력으로부터 읽어서 표준출력, 화일로 쓴다.
.SH 개요
.B tee
[\-ai] [\-\-append] [\-\-ignore-interrupts] [\-\-help] [\-\-version] [화일...]
.SH 설명
이 맨페이지는 GNU 버전의
.BR tee 
를 다룬다.
.B tee
명령은 표준입력으로부터의 입력을 표준출력 또는 인수로 주어진 화일에 복사한다.
.P
씌여질 화일이 존재하지 않으면 생성된다. 만약 이미 존재한다면 
.I \-a
옵션을 사용하지 않는 한 이전의 자료는 모두 지워진다.
.SS 옵션
.TP
.I "\-a, \-\-append"
덮어쓰지 않고 주어진 화일에 표준입력을 추가한다.
.TP
.I "\-\-help"
표준출력으로 사용법을 출력하고 정상적으로 종료한다.
.TP
.I "\-i, \-\-ignore-interrupts"
인터럽트 신호를 무시한다.
.TP
.I "\-\-version"
표준출력으로 버전정보를 출력하고 정상적으로 종료한다.
