.TH TTY 1L "GNU 쉘 유틸리티" "FSF" \" -*- nroff -*-
.SH 이름
tty \- 표준입력이 연결되어 있는 터미널의 화일명을 출력한다.
.SH 개요
.B tty
[\-s] [\-\-silent] [\-\-quiet] [\-\-help] [\-\-version]
.SH 설명
이 맨페이지는 GNU 버전의
.BR tty 
를 설명한다.
.B tty
는 표준입력이 연결되어 있는 터미널의 화일명을 출력한다. 표준입력이 tty 가
아닐 경우에는 `not a tty'라고 출력한다. 종료 상태는 다음과 같다:
.nf
0 표준입력이 tty 일 때
1 표준입력이 tty 가 아닐 때
2 잘못된 인수
3 쓰기 에러 발생
.fi
.SS 옵션
.TP
.I "\-\-help"
표준출력으로 사용법을 출력하고 정상적으로 종료한다.
.TP
.I "\-s, \-\-silent, \-\-quiet"
아무 것도 출력하지 않는다; 단지 종료 코드만 반환한다.
.TP
.I "\-\-version"
표준출력으로 버전정보를 출력하고 정상적으로 종료한다.
