.TH USERS 1L "GNU 쉘 유틸리티" "FSF" \" -*- nroff -*-
.SH 이름
users \- 현재 호스트에 로그인한 사용자의 이름을 출력한다.
.SH 개요
.B users [FILE]
.br
.B users
{\-\-help,\-\-version}
.SH 설명
이 맨페이지는 GNU 버전의
.BR users 
를 설명한다.
.B users
는 현재 호스트에 로그인한 사용자의 이름 목록을 빈칸으로 구분하여 한 줄에 
출력한다.
각 사용자명은 로그인 세션에 해당하는 것으로서 한 사용자가 여러번
로그인하였다면 그 수만큼 출력될 것이다.
화일 인수가 없을 때
.B users
는 
.B /etc/utmp 
화일로부터 정보를 입수한다.
화일 인수가 주어지면
.B users
는 그 화일을 사용한다.
보통은
.B /etc/wtmp 
를 지정한다.
.SS 옵션
.TP
.I "\-\-help"
표준출력으로 사용법을 출력하고 정상적으로 종료한다.
.TP
.I "\-\-version"
표준출력으로 버전정보를 출력하고 정상적으로 종료한다.
