.TH WHO 1L "GNU 쉘 유틸리티" "FSF" \" -*- nroff -*-
.SH 이름
who \- 로그인한 사람들을 보여준다.
.SH 개요
.B who
[\-imqsuwHT] [\-\-count] [\-\-idle] [\-\-heading] [\-\-help]
[\-\-message] [\-\-mesg] [\-\-version] [\-\-writable] [file] [am i]
.SH 설명
이 맨페이지는 GNU 버전의
.BR who 
를 다룬다.
옵션 아닌 인수가 없을 때
.B who
는 현재 로그인한 각 사용자에 대하여 다음 정보를 출력한다:
.RS
.nf

로그인명
터미널 라인
로그인 시간
원격 호스트 또는 X 디스플레이
.fi
.RE
.PP
옵션 아닌 인수가 하나 주어지면,
.B who
는 /etc/utmp 를 사용하지 않고 그 인수를 로그인한 사용자 이름을 담고 있는
화일로 간주하여 사용한다. 보통 /etc/wtmp 를 주면
.B who
는
이전에 로그인했던 사람들의 목록을 보여준다.
.PP
옵션 아닌 인수가 2 개 주어지면,
.B who
는 실행한 사용자에 대한 정보만 출력한다.( 표준입력으로부터 결정 )
전통적으로 두 개의 인수는 `am i'로서 `who am i' 가 된다.
.SS 옵션
.TP
.I \-m
`who am i'와 같음.
.TP
.I "\-q, \-\-count"
로그인명과 로그인한 횟수를 출력한다.
다른 옵션은 무시된다.
.TP
.I \-s
무시된다; 단지 다른 버전의
.BR who 
와 호환되도록 하기 위함이다.
.TP
.I "\-i, \-u, \-\-idle"
로그인 후 사용자가 얼마의 시간, 분 동안 한가하게 있었는지 출력해준다.
`.' 은 바로 방금 전까지도 활동을 하고 있다는 의미이다.
`old' 는 24 시간 이상 한가하게 있었음을 의미한다.
.TP
.I "\-H, \-\-heading"
칼럼 헤더 라인을 출력한다.
.TP
.I "\-w, \-T, \-\-mesg, \-\-message, \-\-writable"
.IR \-s 
와 마찬가지로,
로그인명 다음에 사용자의 메세지 상황을 문자로 출력한다:
.RS
.IP +
\fBwrite\fP 메세지 허가
.IP \-
\fBwrite\fP 메세지 불허
.IP ?
터미널 장치를 찾을 수 없음
.RE
.TP
.I "\-\-help"
표준출력으로 사용법을 출력하고 정상적으로 종료한다.
.TP
.I "\-\-version"
표준출력으로 버전정보를 출력하고 정상적으로 종료한다.
