.TH WHOAMI 1L "GNU 쉘 유틸리티" "FSF" \" -*- nroff -*-
.SH 이름
whoami \- 유효 사용자ID를 출력한다
.SH 개요
.B whoami [\-\-help] [\-\-version]
.SH 설명
이 맨페이지는 GNU 버전의
.BR whoami 
를 다룬다.
.B whoami
는 사용자명에 연관된 현재의 유효 사용자 ID 를 출력한다.
이는 `id \-un' 명령과 같다.
.SS 옵션
.TP
.I "\-\-help"
표준출력으로 사용법을 출력하고 정상적으로 종료한다.
.TP
.I "\-\-version"
표준출력으로 버전정보를 출력하고 정상적으로 종료한다.
