.TH YES 1L "GNU 쉘 유틸리티" "FSF" \" -*- nroff -*-
.SH 이름
yes \- 종료할 때까지 반복적으로 문자열을 출력한다.
.SH 개요
.B yes
[문자열...]
.br
.B yes
{\-\-help,\-\-version}
.SH 설명
이 맨페이지는 GNU 버전의
.BR yes 
를 설명한다.
.B yes
는 명령행 인수들을 스페이스로 구분하여 출력하고 줄바꿈을 하며 강제 종료될
때까지 계속 출력한다. 아무런 인수가 없으면 `y' 라는 문자를 게속 출력한다.
.SS 옵션
GNU
.B false
가 딱 하나의 인수와 함께 실행될 때는 다음 옵션이 인식된다:
.TP
.I "\-\-help"
표준출력으로 사용법을 출력하고 정상적으로 종료한다.
.TP
.I "\-\-version"
표준출력으로 버전정보를 출력하고 정상적으로 종료한다.
